AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
  - 'bin/**/*'
  - 'config/**/*'
  - 'db/**/*'
  - 'vendor/**/*'
  - 'Gemfile.lock'

Style/AsciiComments:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
