#!/usr/bin/env bash
AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
  - 'bin/**/*'
  - 'client/**/*'
  - 'config/**/*'
  - 'db/**/*'
  - 'vendor/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 50
  Exclude:
  - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/AndOr:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false
  Exclude:
  - 'app/controllers/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

Style/StringLiterals:
  EnforcedStyle: single_quotes

ClassAndModuleChildren:
  EnforcedStyle: compact
