version: '3'

services:
  web:
    build: .
    image: examin/rails
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - examin_rails_sync:/examin_rails
    ports:
      - "3500:3000"
    environment:
      RAILS_ENV: "development"
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    build: ./docker/containers/db
    image: examin/db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3316:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  examin_rails_sync:
    external: true
  db_data:
    driver: local
