version: '3'

services:
  web:
    build: .
    image: examin/rails
    volumes:
      - .:/examin_rails:cached
    ports:
      - "3500:3000"
    environment:
      TZ: "Asia/Tokyo"
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: mysql:5.7.24
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3316:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Asia/Tokyo"

volumes:
  db_data:
    driver: local
