default: &default
  adapter: mysql2
  encoding: utf8
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] || 'examin' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'examin' %>
  host: <%= ENV['DATABASE_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DATABASE_PORT'] || 3316 %>
  database: examin

development:
  <<: *default

test:
  <<: *default
  database: examin_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
